name: semana 4 Actv 4 CI
on:
  # Trigger: Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama "master"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:	
# Una ejecución de flujo de trabajo se compone de uno o más trabajos que se pueden ejecutar de forma secuencial o en paralelo.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # uses: actions/checkout@v3
	  
	  #Step 1: Descarga el repositorio
	  - uses: actions/checkout@v2

      # Step 2 y 3: requisitos QEMU y Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 4: construccion y publicacion de la iamgen
      - name: Build and push
		id: docker_build
        uses: docker/build-push-action@v2
		with:
			push: true
			context: .
			file: ./Dockerfile
			tags: |
				mvvera/my-python:v2.0

      # Step 5: muestra el digest de la imagen
      - name: Image digest
        run: |
          echo ${{steps.docker_build.outputs.digest }}
